name: Deploy Testnet

on:
  workflow_dispatch:

jobs:
  job1:
    uses: ./.github/workflows/deploy.yml
    with:
      MODE: dev
      REMOTE_HOST: 47.243.184.31
      NAME: block-explorer-testnet
      BLOCKCHAIN_RPC_URL: https://sepolia-rpc.zkbase.app
      CONTRACT_VERIFICATION_API_URL: https://sepolia-contract-verification.zkbase.app
    secrets: inherit
