name: Deploy Dev

on:
  workflow_dispatch:

jobs:
  job1:
    uses: ./.github/workflows/deploy.yml
    with:
      MODE: dev
      REMOTE_HOST: 47.243.184.31
      NAME: block-explorer-dev
      BLOCKCHAIN_RPC_URL: https://alpha-sepolia-rpc.zkbase.app
      CONTRACT_VERIFICATION_API_URL: https://alpha-sepolia-contract-verification.zkbase.app
      DATA_FETCH_PORT: '4040'
      WORKER_PORT: '4001'
      API_PORT: '4020'
      API_METRICS_PORT: '4005'
      DATABASE_NAME: 'block-explorer-alpha'
    secrets: inherit
