name: Deploy Client Dev

on:
  workflow_dispatch:

jobs:
  job1:
    uses: ./.github/workflows/deploy-client.yml
    with:
      MODE: testnet
      REMOTE_HOST: 47.243.184.31
      NAME: block-explorer-testnet
    secrets: inherit
