name: Refresh Dev

on:
  workflow_dispatch:

jobs:
  job1:
    uses: ./.github/workflows/refresh.yml
    with:
      REMOTE_HOST: xj3-2-1.s.filfox.io
      NAME: block-explorer-dev
      DATABASE_NAME: 'block-explorer-alpha'
      REMOTE_PORT: '17011'
      TARGET_PATH: '/mnt/md0/www/'
      REMOTE_USER: 'ps'
    secrets: inherit
