name: Refresh Testnet

on:
  workflow_dispatch:

jobs:
  job1:
    uses: ./.github/workflows/refresh.yml
    with:
      REMOTE_HOST: xj3-2-1.s.filfox.io
      NAME: block-explorer-testnet
      REMOTE_PORT: '17011'
      TARGET_PATH: '/mnt/md0/www/'
      REMOTE_USER: 'ps'
      PREPARE_SCRIPT: 'PATH=$PATH:/home/ps/.nvm/versions/node/v18.20.3/bin'
      DATABASE_NAME: 'block-explorer-testnet'
    secrets: inherit
