name: Refresh Testnet

on:
  workflow_dispatch:

jobs:
  job1:
    uses: ./.github/workflows/refresh.yml
    with:
      REMOTE_HOST: 47.243.184.31
      NAME: block-explorer-testnet
    secrets: inherit
